### ISSUE TITLE
Not in range error

### ISSUE THREAD

**Issue by somaria** [bierbaumtim/lazy_load_refresh_indicator#1] opened 2020-01-15 22:34 UTC
Getting this particular error here.  I am using basically the exact same configuration with itemCount=20

════════ (130) Exception caught by widgets library ═════════════════════════════════════════════════
RangeError (index): Invalid value: Not in range 0..46, inclusive: 47

return Padding(
//        padding: EdgeInsets.only(bottom: 85),
      padding: EdgeInsets.only(bottom: 0),
      child: LazyLoadRefreshIndicator(
        child: ListView.builder(
          padding: EdgeInsets.only(top: 5.0),
          itemCount: itemCount,
          itemBuilder: (context, index) {
            return _buildListItem(context, snapshot[index]);
          },
        ),
        onEndOfPage: onEndOfPage,
        onRefresh: onRefresh,
        scrollOffset: 150,
        isLoading: isLoading,
      ),
    );

**Comment by bierbaumtim** [comment] 2020-01-16 19:04
I guess that the itemcount does not match with the snapshot.length. 

But it is only a guess. So could you please provide a short main file that reproduces this error.

**Comment by somaria** [comment] 2020-01-16 22:23
I have changed itemCount to the line below and it seems to fix it:

         itemCount: itemCount > snapshot.length ? snapshot.length : itemCount,

**Comment by bierbaumtim** [comment] 2020-01-18 14:18
That won't be necessary. You can always use Snapshot.length. 
The itemCount variable from the example was only there to show that you have to specify the number of items to display, but not that it has to be a fixed int with the value 20. 
If you understood it as a fixed number, I am sorry. I will update the example to make it clearer.

**Comment by somaria** [comment] 2020-01-18 20:04
If I use itemCount: snapshot.length, the endofpage effect of reaching 20 items and load the next 20 items will not be there. 

```Widget _buildBody(BuildContext context) {
    _handleSignInAgain().then((FirebaseUser user) {
      });
    }).catchError((e) => print('no internet connection' + e));

    return StreamBuilder<QuerySnapshot>(
      stream: myStream,
      builder: (context, snapshot) {
        if (!snapshot.hasData) {
          print("no data yet");
          return LinearProgressIndicator();
        }
        return _buildList(context, snapshot.data.documents);
      },
    );
  }

  int itemCount = 20;
  bool isLoading = false;

  Future<void> onRefresh() async => Future.delayed(
        Duration(seconds: 2),
        () => setState(
          () => itemCount = 20,
        ),
      );

  void onEndOfPage() async {
    print("at end of page");
    setState(() => isLoading = true);
    await Future.delayed(Duration(seconds: 2), () {});
    setState(() {
      isLoading = false;
      itemCount += 20;
    });
  }

  Widget _buildList(BuildContext context, List<DocumentSnapshot> snapshot) {
    return Padding(
//        padding: EdgeInsets.only(bottom: 85),
      padding: EdgeInsets.only(bottom: 0),
      child: LazyLoadRefreshIndicator(
        child: ListView.builder(
          physics: AlwaysScrollableScrollPhysics(),
          padding: EdgeInsets.only(top: 5.0),
//          itemCount: itemCount > snapshot.length ? snapshot.length : itemCount,
          itemCount: snapshot.length,
          itemBuilder: (context, index) {
            return _buildListItem(context, snapshot[index]);
          },
        ),
        onEndOfPage: onEndOfPage,
        onRefresh: onRefresh,
        scrollOffset: 100,
        isLoading: isLoading,
      ),
    );
  }
```

**Comment by somaria** [comment] 2020-01-19 10:32
This should work better since the out of range is only by 1 index.

`itemCount: itemCount,
          itemBuilder: (context, index) {
            if (index < snapshot.length) {
              return _buildListItem(context, snapshot[index]);
            } else {
              return null;
            }
          },`

**Comment by bierbaumtim** [comment] 2020-01-19 11:07
The reason why the loading animation is not displayed is that you have not loaded your data lazily. Your QuerySnapshot contains all documents that are currently in the Firestore database. The use case for LazyLoadRefreshIndicator is slightly different. 
As an example, you get 10 documents from the database per http call. The first one returns the first 10 documents, the second call skips the first 10 and returns the next 10 documents and so on. So you make the first call, build the list and in the onEndOfPage callback you make the next http call and adds the returned data to your existing list.

But with some tweaks you can make your current implementation to react like the example.
First convert the buildList method into its own widget.
```
class DocumentsList extends StatefulWidget {
final List<DocumentSnapshot> snapshots;

@override
_DocumentsListState createState()=>_DocumentsListState();
}

class _DocumentsListState extends State<DocumentsList>{
int itemCount;
bool isLoading;

@override
void initState(){
super.initState();
itemCount = snapshot.lenght <= 20 ? snapshot.length : 20;
isLoading = false;
}

  Future<void> onRefresh() async => Future.delayed(
        Duration(seconds: 2),
        () => setState(
          () => itemCount = snapshot.length <= 20 ? snapshot.length : 20,
        ),
      );

  void onEndOfPage() async {
    print("at end of page");
    setState(() => isLoading = true);
    await Future.delayed(Duration(seconds: 2), () {});
    setState(() {
      isLoading = false;
      itemCount = itemCount + 20 <= snapshot.length?itemCount+20:snapshot.length;
    });
  }

@override
  Widget build(BuildContext context) {
    return Padding(
//        padding: EdgeInsets.only(bottom: 85),
      padding: EdgeInsets.only(bottom: 0),
      child: LazyLoadRefreshIndicator(
        child: ListView.builder(
          physics: AlwaysScrollableScrollPhysics(),
          padding: EdgeInsets.only(top: 5.0),
//          itemCount: itemCount > snapshot.length ? snapshot.length : itemCount,
          itemCount: itemCount,
          itemBuilder: (context, index) {
            return _buildListItem(context, snapshot[index]);
          },
        ),
        onEndOfPage: onEndOfPage,
        onRefresh: onRefresh,
        scrollOffset: 100,
        isLoading: isLoading,
      ),
    );
  }
```

Second replace _buildList method in the StreamBuilder with this new Widget
```
return StreamBuilder<QuerySnapshot>(
      stream: myStream,
      builder: (context, snapshot) {
        if (!snapshot.hasData) {
          print("no data yet");
          return LinearProgressIndicator();
        }
        return DocumentsList(snapshot.data.documents);
      },
    );
```
Now it should look like you load your data lazily and the OutOfRangeException should also be solved

**Comment by somaria** [comment] 2020-01-19 22:17
Ok, now I understand.

**Comment by bierbaumtim** [comment] 2020-01-23 14:07
Ok perfect so i'll close this issue

**Closed as completed by bierbaumtim** 2020-01-23 14:07 UTC
